default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: 5

development:
  <<: *default
  database: Dsoft_development
  username: admin
  password: 44262718
  host: localhost
  port: 5432

  
production:
  <<: *default
  database: Dsoft_production
  username: admin
  password: 44262718
